//lesson4.2==============================
["Я всё вижу",
 "Моя сестра живёт там",
 "Этот урок кажется интересным",
 "Этот урок помогает мне",
 "Я всё понимаю",
 "Мои родители знают это",
 "Её брат часто говорит это",
 "То предложение кажется странным",
 "Мой босс всегда говорит это",
 "Его уроки кажутся очень полезными",
 "Мой брат хочет это",
 "У его отца есть машина",
 "Мои родители хотят сделать это",
 "Твои уроки реально помогают",
 "Моя сестра учится там",
 "Эти уроки помогают мне",
 "Они всё знают",
 "Мой брат пытается сделать это",
 "Их идеи кажутся очень интересными",
 "Мой босс обычно проверяет всю информацию",
 "Моя сестра живёт в этом месте",
 "У моего друга есть машина",
 "У него есть компания",
 "Её прибыль кажется такой большой",
 "Мой босс всё знает",
 "Наша мама думает так же",
 "Мой босс читает все документы",
 "Эти уроки кажутся очень полезными",
 "Это предложение выглядит интересным",
 "У этой компании есть деньги",
 "Эти уроки реально помогают",
 "Я чувствую это",
 ];

 ["I see everything",
  "My sister lives there",
  "This lesson seems interesting",
  "This lesson helps me",
  "I understand everything",
  "My parents know it",
  "Her brother often says it",
  "That offer seems strange",
  "My boss always says it",
  "His lessons seem very useful",
  "My brother wants it",
  "His father has a car",
  "My parents want to do it",
  "Your lessons really help",
  "My sister studies there",
  "There lessons help me",
  "They know everythink",
  "My brother tries to do it",
  "Their ideas seem very interesting",
  "My boss usually checks all the information",
  "My sister lives in this place",
  "My friend has a car",
  "He has a company",
  "Its profit seems so big",
  "My boss knows everything",
  "Our mother thinks the same",
  "My boss reeds all the documents",
  "These lessons seem very useful",
  "This offer looks interesting",
  "This company has money",
  "These lessons really help",
  "I feel it",
];

 //lesson7.1=======================================================
 //become - стать
 ["Мне нравится это видео",
  "Мне нравится эта вещь",
  "Я хотел бы выпить чашку кофе",
  "Мне нравится этот плейлист",
  "Я хотел бы сделать это",
  "Я хотел бы посетить это место",
  "Я хотел бы чашку кофе",
  "Я хотел бы стать бизнесменом",
  "Она хотела бы стать учительницей",
  "Ему нравится это платье",
  "Я вижу, тебе реально нравится английский",
  "Моему другу нравится этот отель",
  "Мне нравится английский",
  "Мне действительно нравится этот плейлист",
  "Мне нравится этот канал",
  "Ей нравится это место",
  "Тебе нравится это",
  "Ей нравится это",
  "Я вижу, ему это реально нравится",
  "Мне действително нравится этот канал",
  "Я хотел бы знать английский очень хорошо",
  "Им нравится это",
  "Мне нравится это",
  "Я хотел бы выпить чашку чая",
  "Я знаю, им это нравится",
  "Мне нравится этот метод",
  "Нам нравится это",
  "Я хотел бы чашку чая",
  "Мне так же нравится этот канал",
  "Мне нравится этот канал так же",
  "Мне реально нравится это место",
  "Мне реально это нравится",
  "Он хотел бы стать врачом",
  "Мне нравятся твои уроки",
  "Я хотел бы стать бизнесменом",
  "Мне реально нравятя эти уроки",
  "Я хотел бы стать менеджером",
  "Мне нравится эта идея",
  "Я хотел бы поехать за границу",
  "Она хотела бы поехать в другое место",
];

  ["I like this video",
   "I like this thing",
   "I`d like to drink a cup of coffee",
   "I like this playlist",
   "I`d like to do it",
   "I`d like to visit this place",
   "I`d like a cup of coffee",
   "I`d like to become a businessman",
   "She`d like to become a teacher",
   "He likes this dress",
   "I see you really like English",
   "My friend likes this hotel",
   "I like English",
   "I really like this playlist",
   "I like this shannel",
   "She likes this place",
   "You like it",
   "She likes it",
   "I see he really likes it",
   "I really like this shannel",
   "I`d like to know English very well",
   "They like it",
   "I like it",
   "I`d like to drink a cup of tea",
   "I know they like it",
   "I like this method",
   "We like it",
   "I`d like a cup of tea",
   "I also like this shannel",
   "I like this cshannel, too",
   "I really like this place",
   "I really like it",
   "He`d like to become a doctor",
   "I like your lessons",
   "I`d like to become a businessman",
   "I really like these lessons",
   "I`d like to become a manager",
   "I like this idea",
   "I`d like to go abroad",
   "She`d like to go to another place",
];


//lesson 8===========================================================
//Present Simple (negative form) - простое настоящее время (негативная форма, отрицание)
//I, We, You, They + don't + verb
//He, She, It + doesn't + verb (s к глаголу при отрицании не добавляется, добавляется только в утверждении - He wants, He doesn't want)
//agree diskuss later
//говорить на каком-то языке - speak
//просто что-то сказать - say
//если сказать кому-то - tell (tell me, I tell you)
  ["Я знаю",
   "Я не знаю",
   "Мы понимаем",
   "Мы не понимаем",
   "Ты пытаешься выучить английский",
   "Ты не пытаешься выучить английский",
   "Они помогают мне",
   "Они не помогают мне",
   "Я согласен с тобой",
   "Я не согласен с тобой",
   "Мне нравится это",
   "Мне не нравится это",
   "Я хочу учиться там",
   "Я не хочу учиться там",
   "Я хочу обсудить это",
   "Я не хочу обсуждать это",
   "Я хочу сделать это прямо сейчас",
   "Я не хочу делать это прямо сейчас",
   "Я хочу сделать это позже",
   "Я не хочу говорить это",
   "Я не хочу говорить тебе эту вещь",
   "Я не хочу говорить тебе об этой проблеме",
   "Я не хочу думать об этом",
   "Он знает это",
   "Он не знает это",
   "Она не хочет обсуждать это",
   "Это не помогает мне",
   "Это не кажется странным",
   "Это не работает",
  ];

   ["I know",
    "I don't know",
    "We understand",
    "We don't understand",
    "You try to learn English",
    "You don't try to learn English",
    "They help me",
    "They don't help me",
    "I agree with you",
    "I don't agree with you",
    "I like it",
    "I don't like it",
    "I want to study there",
    "I don't want study there",
    "I want to discuss it",
    "I don't want to discuss it",
    "I want to do it right now",
    "I don't to do it right now",
    "I want to do it later",
    "I don't want to say it",
    "I won't want to tell you this thing",
    "I don't want to tell you about rhis problem",
    "I don't want to think about it",
    "He knows it",
    "He doesn't know it",
    "She doesn't want to discuss it",
    "It doesn't help me",
    "It doesn't seem strange",
    "It doesn't work",
  ];

//8.1
//those - те
//there - там
//that - тот
    ["Ты не пытаешься выучить английский",
     "Это не работает",
     "Я не хочу это знать",
     "Я не согласен с тобой",
     "Мне не нравится это",
     "Она не хочет обсуждать это",
     "Он не работает там",
     "Он работает здесь",
     "Он не знает это",
     "Это не кажется странным",
     "Я не знаю",
     "Она не помнит это",
     "Он не хочет читать эти книги",
     "Он хочет читать те книги",
     "Я не хочу говорить это",
     "У него нет этой информации",
     "Я не хочу играть в компьютерные игры",
     "Я не знаю этого человека",
     "Я не хочу делать это прямо сейчас",
     "Он не хочет пытаться найти хорошую работу",
     "Он не пытается найти хорошую работу",
     "Я не хочу жить в этой стране",
     "Мой друг не думает так",
     "Я не хочу говорить тебе об этой проблеме",
     "Я не хочу учиться там",
     "Мы не хотим жить в другом месте",
     "Это не кажется полезным",
     "Они не помогают мне",
     "Я не хочу говорить тебе эту вещь",
     "Я не хочу думать об этом",
     "Я не понимаю этих людей",
     "Мы не понимаем это",
     "Я не хочу обсуждать это",
     "У него нет машины",
     "Я не хочу пить",
     "Я не хочу жить в том городе",
     "Это не помогает мне",
   ];

     ["You don't try to learn Ebglish",
      "It doesn't work",
      "I don't want to know it",
      "I don't agree with you",
      "I don't like it",
      "She doesn't want to discuss it",
      "He doesn't work there",
      "He works here",
      "He doesn't know it",
      "It doesn't seem strange",
      "I don't know",
      "She doesn't remember it",
      "He doesn't want to read these books",
      "He wants to read those books",
      "I don't want to say it",
      "He doesn't have this information",
      "I don't want to play computer games",
      "I don't know this person",
      "I don't want to do it right now",
      "He doesn't want to try to find a good job",
      "He doesn't try to find a good job",
      "I don't want to leave in this country",
      "My friend doesn't think so",
      "I don't want to tell you about this problem",
      "I don't want to study there",
      "We don't want to leave in another place",
      "It doesn't seem useful",
      "They don't help me",
      "I don't want to tell you this thing",
      "I don't want to think about it",
      "I don't understand this people",
      "We doesn't understand it",
      "I don't want to discuss it",
      "He doesn't have a car",
      "I don't want to drink",
      "I don't want to leave in that city",
      "It doesn't help me",
      ];


//lesson 9
//interest - интересовать
//me - меня
//attract - привлекать
//recommend - рекомендовать
//change - изменить
//partner - партнёр
//him - его (не знает его, не верит ему)
//his - его (его книга)
//them - им (не звоним им)
//us - нам (верит нам)
//their - их
//My friend and I - мы с моим другом
//money в англицском языке неисчисляемы, поэтому они it
//bring - приносить
//happy - счастливый
//happiness - счастье
//неисчисляемому неопределенный артикль не нужен
// если прилагательное и существительное в единственном числе, то ставится артикль а, если существительное во множественном числе, то не ставится
//make - делать (делать кого-то далее прилагательное)
//late - поздно
//later- позже
//Its - его, её(когда речь идёт о неодушевлённом предмете)
      ["Эта вещь не интересует меня",
       "Эти вещи не привлекают меня",
       "Та вещь не кажется интересной",
       "Те вещи не кажутся странными",
       "Те уроки не кажутся полезными",
       "Эти уроки кажутся очень полезными",
       "Тот метод не помогает",
       "Этот метод реально помогает",
       "Мой брат не хочет думать о своём будущем",
       "Моя сестра не знает этого человека",
       "Мои друзья не рекомендуют этот отель",
       "Его сын не хочет стать доктором",
       "Её дочь не хочет учиться там",
       "Его родители не чувствуют себя счастливыми",
       "Этот человек не пытается изменить свою жизнь",
       "Мой босс не видит её",
       "Мой партнёр не знает его",
       "Мы с моим другом не звоним им",
       "Наш учитель не верит нам",
       "Он думает деньги не приносят людям счастье",
       "Она думает деньги не делают людей счастливыми",
       "Я действительно хочу сделать вас счастливыми",
     ];

     ["This thing doesn't interest me",
      "These things don't attract me",
      "That thing doesn't seem interesting",
      "Those things don't seem strange",
      "Those lessons don't seem useful",
      "These lessons seem very useful",
      "That method doesn't help",
      "This method really helps",
      "My brother doesn't want to think about his future",
      "My sister doesn't know this person",
      "My friends don't recommended this hotel",
      "His son doesn't want to become a doctor",
      "Her daughter doesn't want to learn there",
      "His parents don't feel happy",
      "This person doesn't try to change his life",
      "My boss doesn't see her",
      "My partner doesn't know him",
      "My friend and I don't call them",
      "Our teacher doesn't believe us",
      "He thinks money doesn't bring peoele happiness",
      "She thinks money doesn't make people happy",
      "I reallywant to make you happy",
    ];

    //lesson 9.1========================================================================
    //fluently - свободно, бегло
    ["То предложение не кажется странным",
     "Его босс не говорит по английски свободно",
     "Мои родители не обсуждают это",
     "Эти вещи не привлекают меня",
     "Те вещи не кажутся странными",
     "Его сын не хочет стать доктором",
     "Наш учитель не верит нам",
     "Мой партнёр не знает его",
     "Моему другу не нравится эта идея",
     "Она думает деньги не делают людей счастливыми",
     "Этот человек не пытается изменить свою жизнь",
     "Мой босс не видит её",
     "Эта вещь не привлекает меня",
     "Мои друзья не рекомендуют этот отель",
     "Моя сестра не знает этого человека",
     "Мой брат не хочет думать о своём будущем",
     "Мы с моим другом не звоним им",
     "Мой друг не думает так",
     "Мой друг не думает так же",
     "Те уроки не кажутся полезными",
     "Эти уроки кажутся очень полезными",
     "Моя сестра не хочет делать это позже",
     "Она хочет сделать это прямо сейчас",
     "Эта вещь не интересует меня",
     "Её прибыль не кажется большой",
     "Мой друг не пытается делать это",
     "Их компания не пытается делать это",
     "Та вещь не кажется интересной",
     "Моя сестра не хочет учиться там",
     "Тот метод не работает",
     "Этот метод реально помогает",
     "Их родители не чувствуют себя счастливыми",
     "Он думает деньги не приносят людям счастье",
     "Это предложение не кажется таким интересным",
     "Наша компания не хочет этого",
     "Мой друг не согласен со мной",
   ];

   ["That offer doesn't seem strange",
    "His boss doesn't speak English fluently",
    "My parents don't diskuss it",
    "These things don't attract me",
    "Those things don't seem strange",
    "His son doesn't want to become a doctor",
    "Our teacher doesn't believe us",
    "My partner doesn't know him",
    "My friend doesn't like this idea",
    "She thinks money doesn't make people happy",
    "This person doesn't try to change his life",
    "My boss doesn't see her",
    "This thing doesn't attract me",
    "My friends don't recommend this hotel",
    "My sister doesn't know this person",
    "My brother doesn't want think about his future",
    "My friend and I don't call them",
    "My friend doesn't think so",
    "My friend doesn't think the same",
    "Those lessons don't seem useful",
    "These lessons seem very useful",
    "My sister doesn't want to do it late",
    "She wants to do it right now",
    "This thing doesn't interest me",
    "Its profit doesn't seem big",
    "My friend doesn't try to do it",
    "Their company doesn't try to do it",
    "That thing doesn't seem interesting",
    "My sister doesn't want to study there",
    "That method doesn't work",
    "This method really helps",
    "Their parents don't fill happy",
    "He think money doesn't bring people happiness",
    "This offer doesn't seem so interesting",
    "Our company doesn't want it",
    "My friend doesn't agree with me",
  ];

//lesson 10==============
// I need it -  мне нужно это
// hard - усердно
// harder - усердней
// correct - исплавлять
// I need to solve this problem -  мне нужно решить эту проблему(устойчивое выражение)
// remember - запомнить
// rule - правило
// improve - улучшить
// any - каких-либо
// at all - вовсе, ставится в конце
// advice - совет
// less - меньше
// correctly - правильно
  ["Мне нужна эта информация",
   "Мне нужна эта вещь",
   "Мне нужно сделать это",
   "Мне нужно проверить это",
   "Мне нужно учиться усердней",
   "Мне нужно выучить английский",
   "Мне нужно исправить эту ошибку",
   "Мне нужно увидеть её",
   "Мне нужно позвонить ему",
   "Мне нужно позвонить им",
   "Мне нужно это",
   "Нам нужно это",
   "Тебе нужно это",
   "Им нужно это",
   "Ему нужно это",
   "Ей нужно это",
   "Мне реально нужен английский",
   "Мне реально это нужно",
   "Ты мне действительно нужна",
   "Мне действително нужно знать английский",
   "Мне реально нужны твои уроки",
   "Мне нужно решить эту проблему",
   "Ей нужно исправить эти ошибки",
   "Ему нужно найти хорошую работу",
   "Тебе нужно запомнить это правило",
   "Тебе нужно запомнить это",
   "Мне нужно улучшить свой английский",
   "Мне нужно говорить по-английски без ошибок",
   "Мне нужно говорить по-английски вовсе без каких-либо ошибок",
   "Моему другу нужна твоя помощь",
   "Моему другу нужет твой совет",
   "Мне нужен твой совет",
   "Его отцу нужны деньги",
   "Твоей маме нужно работать меньше",
 ];

 ["I need this information",
  "I need this thing",
  "I need to do it",
  "I need to check it",
  "I need to study harder",
  "I need to learn English",
  "I need to correct this mistake",
  "I need to see her",
  "I need to call him",
  "I need to call them",
  "I need it",
  "We need it",
  "You need it",
  "They need it",
  "He needs it",
  "She needs it",
  "I really need English",
  "I really need it",
  "I really need you",
  "I really need to know English",
  "I really need your lessons",
  "I need to solve this problem",
  "She needs to correct these mistakes",
  "She needs to find a good job",
  "You need to remember this rule",
  "You need to remember it",
  "I need to improve my English",
  "I need to speak English without mistakes",
  "I need to speak English without any mistakes at all",
  "My friend needs your help",
  "My friend needs your advice",
  "His father needs money",
  "Your mother needs to work less",
];


// lesson 10.1===========================================
["Мне нужно говорить по-английски вовсе без каких-либо ошибок",
 "Мне нужно это",
 "Твоей маме нужно работать меньше",
 "Мне нужно позвонить им",
 "Мне нужно исправить эту ошибку",
 "Ей нужно исправить эти ошибки",
 "Мне нужна эта информация",
 "Мне нужно говорить по-английски правильно",
 "Тебе нужно запомнить это",
 "Мне нужно улучшить свой английский",
 "Мне нужно учиться усердней",
 "Мне нужно позвонить ему",
 "Мне реально нужен английский",
 "Мне нужно говорить по-английски без ошибок",
 "Мне нужно решить эту проблему",
 "Ему нужно найти хорошую работу",
 "Мне нужно говорить по-английски свободно",
 "Его отцу нужны деньги",
 "Нам нужно больше информации",
 "Ему нужно изменить свою жизнь",
 "Мне действительно нужны твои уроки",
 "Мне реально нужно это знать",
 "Мне нужно решить эти проблемы",
 "Мне нужно проверить это",
 "Мне нужен твой совет",
 "Мне нужно выучить английский",
 "Мне нужна эта вещь",
 "Тебе нужно запомнить это правило",
 "Мне нужно сделать это",
 "Им нужно это",
 "Тебе нужно это",
 "Ему нужно больше денег",
 "Моему другу нужна твоя помощь",
 "Нам нужно это",
 "Я думаю, тебе нужно работать меньше",
 "Мне нужно увидеть её",
 "Мне реально это нужно",
 "Мне нужно решить ту проблему",
 "Моему партнёру нужно решить те проблемы",
 "Ты мне реально нужна",
 "Мне нужны деньги",
 "Ей нужен твой совет",
 "Ей нужно это",
 "Ему нужно это",
 "Я думаю, тебе нужно работать больше",
 "Моему другу нужен твой совет прямо сейчас",
];


["I need speak English without any mistakes at all",
 "I need it",
 "Your mother needs to work less",
 "I need to call them",
 "I need to correct this mistake",
 "She heeds to correct these mistakes",
 "I need this information",
 "I need speak English correctly",
 "You need to remember it",
 "I need to improve my English",
 "I need to study harder",
 "I need to call him",
 "I really need English",
 "I need speak English without mistakes",
 "I need to solve this problem",
 "He needs to find a good job",
 "I need to speak English fluently",
 "His father needs money",
 "We need more information",
 "He needs to change his life",
 "I really need your lessons",
 "I really need to know it",
 "I need to solve these problems",
 "I need to check it",
 "I need your advice",
 "I need to learn English",
 "I need this thing",
 "You need to remember this rule",
 "I need to do it",
 "They need it",
 "You need it",
 "He needs more money",
 "My friends needs your help",
 "We need it",
 "I think you need to work less",
 "I need to see her",
 "I really need it",
 "I need to solve that problem",
 "My partner needs to solve those problems",
 "I really need you",
 "I need money",
 "She needs your advice",
 "She needs it",
 "He needs it",
 "I think you need to work more",
 "My friend needs your advice right now",
];


// lesson 11========================
// Present Simple Tense - настоящее простое время
// support - поддержка
// better - лучше
// pay - платить
// happen - случаться
// from time to time - время от времени
// so many - так много
// ch, ss, sh, x, + es
// order - заказывать
// motivate - мотивировать
// explane - объяснять
["Я согласен с тобой",
 "Мы поддерживаем тебя",
 "Ты знаешь это лучше",
 "Они живут в другой стране",
 "Он всегда платит за неё",
 "Она согласна с тобой",
 "Это происходит время от времени",
 "Он часто ходит в кино",
 "Она ходит на работу",
 "У него так много проблем",
 "У него есть интересная идея",
 "Она преподаёт испанский",
 "Я не заказываю еду там",
 "У нас нет каких-либо вопросов",
 "Ты не понимаешь нас",
 "Они не верят ему",
 "Она не говорит мне эти вещи",
 "Он не говорит по-испански",
 "Это не мотивирует меня",
 "Его девушка всё знает",
 "Наши учителя не объясняют это",
 "Его девушка не чувствует себя счастливой",
 "Её парень не знает об этой проблеме",
];


["I agree with you",
 "We support you",
 "You know it better",
 "They live in another country",
 "He always pays for her",
 "She agrees with you",
 "It happens from time to time",
 "He often goes to the cinema",
 "She goes to work",
 "He has so many problems",
 "He has an interesting idea",
 "She teaches Spanish",
 "I don't order food there",
 "We don't have any questions",
 "You don't understand us",
 "They don't believe him",
 "She doesn't tell me these things",
 "She doesn't speak Spanish",
 "It doesn't motivate me",
 "His girlfriend knows everythink",
 "Our teachers don't explain it",
 "His girlfriend doesn't feel happy",
 "Her boyfriend doesn't know about this problem",
];

// lesson 12==========================================
// as soon as possible - кк можно скорее
// train - тренировать
// memory - память
// regularly - регулярно
[ "Мне нравится это",
  "Нам нравится это",
  "Тебе нравится это",
  "Им нравится это",
  "Ему нравится это",
  "Ей нравится это",
  "Мне реально нравится этот канал",
  "Мне также нравится этот плейлист",
  "Я хотел бы чашку кофе",
  "Я хотел бы чашку чая",
  "Я хотел бы знать больше английских слов",
  "Я хотел бы обсудить это с тобой",
  "Мне нужно это",
  "Нам нужно это",
  "Тебе нужно это",
  "Им нужно это",
  "Ему нужно это",
  "Ей нужно это",
  "Мне нужно позвонить ему",
  "Мне нужно позвонить ей",
  "Мне нужно позвонить им",
  "Мне реально нужны эти уроки",
  "Мне реально нужно выучить английский как можно скорее",
  "Я хочу сделать это",
  "Я хотел бы сделать это",
  "Мне нужно сделать это",
  "Я пытаюсь сделать это",
  "Я хочу тренировать свою память",
  "Я хочу тренироваться более регулярно",
  "Нам нужно заплатить за это",
  "Он пытается найти больше времени для английского",
];

[ "I like it",
  "We like it",
  "You like it",
  "They like it",
  "He likes it",
  "She likes it",
  "I really like this shannel",
  "I also like this playlist",
  "I'd like a cup of coffee",
  "I'd like a cup of tea",
  "I'd like to know more English words",
  "I'd like to discuss it with you",
  "I need it",
  "We need it",
  "You need it",
  "They need it",
  "He needs it",
  "She needs it",
  "I need to call him",
  "I need to call her",
  "I need to call them",
  "I really need these lessons",
  "I really need to learn English as soon as possible",
  "I want to do it",
  "I'd like to do it",
  "I need to do it",
  "I try to do it",
  "I want to train my memory",
  "I want to train more regularly",
  "We need to pay for it",
  "He tryes to find more time for English",
];


// lesson 13======================================
// noun - существительное
// ajective - прилагательное
// word order - порядок слов
[ "Мы часто ходим в кино",
  "Я хожу на работу",
  "Я хожу в школу",
  "Мне нужно идти домой",
  "Она обычно приходит домой рано",
  "Она обычно приходит домой поздно",
  "Она обычно приходит домой позже",
  "Он хочет жить в другом месте",
  "У нас нет артикля",
  "Этот метод реально работает",
  "У него есть машина",
  "У неё есть дом",
  "У него новая машина",
  "У неё красивый дом",
  "Я знаю всё",
  "Он читает все документы",
  "Все люди делают это",
  "Я вовсе не понимаю это",
  "Ты говоришь по-английски очень хорошо",
  "Он работает очень усердно",
  "Её(компании) прибыль кажется большой",
  "Успех",
  "Привлекать",
  "Скучать",
  "Прибыль",
  "Поддерживать",
  "Мотивировать",
  "Правило",
  "Совет",
  "Регулярно",
  "Вопрос",
  "Память",
  "Происходить, случаться",
  "Объяснять",
  "За границей",
  "Родители",
  "Обсуждать",
  "Другой",
  "Снова, опять",
  "Ещё один раз",
  "Выучить английский быстро",
  "Говорить по-английски свободно",];

[ "We often go to the cinema",
  "I go to work",
  "I go to school",
  "I need to go home",
  "She usually comes home early",
  "She usually comes home late",
  "She usually comes home later",
  "She wants to live in another place",
  "We don't have an article",
  "This method really works",
  "He has a car",
  "She has a house",
  "He has a new car",
  "She has a beautiful house",
  "I know everything",
  "He reeds all the documents",
  "All people do it",
  "I don't understand it at all",
  "You speak English very well",
  "He works very hard",
  "Its profit seems big",
  "Success",
  "Attract",
  "Miss",
  "Profit",
  "Support",
  "Motivate",
  "Rule",
  "Advice",
  "Regularly",
  "Question",
  "Memory",
  "Happen",
  "Explain",
  "Abroad",
  "Parents",
  "Discuss",
  "Another",
  "Again",
  "One more time",
  "Learn English fast",
  "Speak English fluently",
];

// lesson 11.1 practice=======================================
[ "Он обычно приходит домой поздно",
  "Моя девушка живёт в другом месте",
  "Мы хотим знать английский",
  "Это не работает",
  "Те вещи вовсе не интересуют меня",
  "Я хочу выучить английский быстро",
  "Мне нравится английский",
  "Мы не понимаем это",
  "Я не хочу жить в этой стране",
  "У меня так много интересных идей",
  "Тебе нужно запомнить это",
  "Эта вещь не интересует меня",
  "Я вижу её успех",
  "Я не верю ему",
  "Она хотела бы поехать в другое место",
  "Ему нравится это платье",
  "Мне действительно нужно больше практики",
  "Ему нужно найти хорошую работу",
  "Тебе нужно это",
  "Тебе нравится это",
  "Мне нужно улучшить свой английский",
  "Мне нужно знать английский лучше",
  "Ты мне действительна нужна",
  "Я хочу тренировать свою память",
  "Он хотел бы стать врачом",
  "Я хотел бы выпить чашку кофе",
  "Мой босс обычно проверяет всю информацию",
  "Она хотела бы стать учительницей",
  "Ты очень хорошо говоришь по-английски",
  "Мой брат ходит на работу",
  "Мой друг не думает также",
  "У него нет этой информации",
  "Я не верю ей",
  "Мы не хотим жить в другом месте",
  "Я хочу это",
  "Та вещь не кажется интересной",
  "Мне нравятся твои уроки",
  "Она не помнит это",
  "Я хочу эту вещь",
  "Мы хотели бы заказать это прямо сейчас",
  "Мне нравится эта вещь",
  "Он скучает по тебе",
  "Эти вещи не привлекают меня",
  "У этой компании есть деньги",
  "Нам нужно пойти домой",
  "Я поддерживаю тебя",
  "Я вовсе не знаю это",
  "Она согласна с тобой",
  "У него так много друзей",
  "Ты не понимаешь нас",
];


[
  "He usually comes home late",
  "My girlfriend lives in another place",
  "We wants to know English",
  "It doesn't work",
  "Those things don't interest me at all",
  "I want to learn English fast",
  "I like English",
  "We don't understand it",
  "I don't want to live in this country",
  "I have so many interesting ideas",
  "You need to remember it",
  "This thing doesn't interest me",
  "I see its success",
  "I don't believe him",
  "She'd like to go to another place",
  "He likes this dress",
  "I really need more practice",
  "He needs to find a good job",
  "You need it",
  "You like it",
  "I need to improve my English",
  "I need to know English better",
  "I really need you",
  "I want to train my memory",
  "He'd like to become a doctor",
  "I'd like to drink a cup of coffee",
  "My boss usually checks all the information",
  "She'd like to become a teacher",
  "You speak English very well",
  "My brother goes to work",
  "My friend doesn't think the same",
  "He doesn't have this information",
  "I don't believe her",
  "Me don't want to live in another place",
  "I want it",
  "That thing doesn't seem interesting",
  "I like your lessons",
  "She doesn't remember it",
  "I want this thing",
  "We'd like to order it right now",
  "I like this thing",
  "He misses you",
  "These things don't attract me",
  "This company has money",
  "We need to go home",
  "I support you",
  "I don't know it at all",
  "She agrees with you",
  "He has so many friends",
  "You don't understand us",
];

// lesson 11.2 practice===================================
[
  "Она скучает по тебе",
  "Мне также нравится этот канал",
  "Я не хочу говорить это",
  "Мой друг думает так",
  "Этот человек не пытается изменить свою жизнь",
  "Он ходит на работу",
  "Эта вещь не привлекает меня",
  "Тебе нужно запомнить это правило",
  "Мне реально нравится это",
  "Я не знаю",
  "Я хочу пойти туда",
  "Их прибыль кажется хорошей",
  "Мне нравится этот канал тоже",
  "Его девушка поддерживает его",
  "Я не хочу обсуждать это",
  "Ему нужно изменить свою жизнь",
  "Мой брат не хочет думать о своём будущем",
  "Я хочу хорошую машину",
  "Ему нужно это",
  "Я хотел бы знать больше английских слов",
  "Он не пытается найти хорошую работу",
  "Нам нужно решить эту проблему",
  "Я не думаю так",
  "То предложение не кажется странным",
  "Мой друг хочет жить за границей",
  "Она преподаёт испанский",
  "Я обычно прихожу на работу рано",
  "Я зною его",
  "Моя сестра не знает этого человека",
  "Все люди делают это",
  "Я не хочу знать это",
  "Мне нужно проверить это",
  "Мой босс читает все документы",
  "Ей нравится это",
  "Она хочет сделать это",
  "Мне нравится это",
  "Твоей маме нужно работать меньше",
  "Я хочу сделать это",
  "Я хочу поблагодарить тебя",
  "Я вижу, ему это реально это нравится",
  "Я думаю, тебе нужно работать меньше",
  "Она любит его",
  "Он всегда платит за неё",
  "Моя сестра ходит в школу",
  "Мы с моим другом не звоним им",
  "Мне нужно учиться усерднее",
  "Я хочу быть счастливым",
  "Мой друг не верит ему",
  "Он часто ходит в кино",
  "Он пытается найти больше времени для английского",
];

[
  "She misses you",
  "I also like this shannel",
  "I don't want to say it",
  "My friend thinks so",
  "This person doesn't try to change his life",
  "He goes to work",
  "This thing doesn't attract me",
  "You need to remember this rule",
  "I really like it",
  "I don't know",
  "I want to go there",
  "Their profit seems good",
  "I like this channel, too",
  "His girlfriend supports him",
  "I don't want to discuss it",
  "He needs to change his life",
  "My brother doesn't want to think about his future",
  "I want a good car",
  "He needs it",
  "I'd like to know more English words",
  "He doesn't try to find a good job",
  "We need to solve this problem",
  "I don't think so",
  "That offer doesn't seem strange",
  "My friend wants to live abroad",
  "She teaches Spanish",
  "I usually come to work early",
  "I know him",
  "My sister doesn't know this person",
  "All people do it",
  "I don't want to know it",
  "I need to cheek it",
  "My boss reeds all the documents",
  "She likes it",
  "She wants to do it",
  "I like it",
  "Your mother needs to work less",
  "I want to do it",
  "I want to thank you",
  "I see he really like it",
  "I think you need to work less",
  "She loves him",
  "He always pays for her",
  "My sister goes to school",
  "My friend and I don't call them",
  "I need to study harder",
  "I want to be happy",
  "My friend doesn't believe him",
  "He often goes to the cinema",
  "He tryes to find more time for English",
];

// lesson 12.1 practice=====================================
[
  "Это не мотивирует меня",
  "Я знаю, им это нравится",
  "Я хотел бы поехать за границу",
  "Они не помогают мне",
  "Мои друзья не рекоммендуют этот отель",
  "Мне не нравится это",
  "Я хочу говорить по-английски без ошибок",
  "Им нравится это",
  "Это не кажется странным",
  "Он не говорит по-испански",
  "Я знаю их",
  "Нам нравится это",
  "Он любит её",
  "Я хочу знать эти правила",
  "Ей нужен твой совет",
  "Я хочу улучшить свою грамматику",
  "Их компания не пытается делать это",
  "Мне реально это нужно",
  "Он обычно приходит на работу поздно",
  "Я хотел бы посетить это место",
  "Мне реально нравятся эти уроки",
  "Я хочу этот компьютер",
  "Мне нужна эта вещь снова",
  "Наша компания не хочет этого",
  "Я хочу говорить по-английски лучше",
  "Мои родители не обсуждают это",
  "Наши учителя не объясняют это",
  "Её нужно исправить эти ошибки",
  "Его сын не хочет стать врачом",
  "Это не кажется полезным",
  "Они живут в другой стране",
  "Это предложение не кажется таким интересным",
  "Он хочет купить эту вещь",
  "Я хочу поехать туда снова",
  "У меня новая машина",
  "Я хочу поехать туда ещё один раз",
  "Мой друг хочет проверить это ещё один раз",
  "Я действительно хочу это знать",
  "Он работает здесь",
  "Мы хотим знать все эти правила",
  "Они хотят выучить английский быстро",
  "Она хочет сделать это прямо сейчас",
  "Её(компании) прибыль не кажется большой",
  "Нам нужно это",
  "Я хочу поехать за границу",
  "У него есть компания",
  "Её(компании) прибыль кажется такой большой",
  "У него есть новый дом",
  "Я не хочу говорить тебе эту вещь",
  "Мне нужно позвонить ему",
];


[
  "It doesn't motivate me",
  "I know they like it",
  "I'd like to go abroad",
  "They don't help me",
  "My friends don't recommend this hotel",
  "I don't like it",
  "I want to speak English without mistakes",
  "Them like it",
  "It doesn't seem strange",
  "He doesn't speak Spanish",
  "I know them",
  "We like it",
  "He loves her",
  "I want to know these rules",
  "She needs your advice",
  "I want to improve my grammar",
  "Their company doesn't try to do it",
  "I really need it",
  "He usually comes to work late",
  "I'd like to visit this place",
  "I really like these lessons",
  "I want this computer",
  "I need yhis thing again",
  "Our company doesn't want it",
  "I want to speak English better",
  "Me parents don't discuss it",
  "Our teachers don't explane it",
  "She needs to correct these mistakes",
  "His son doesn't want to become a doctor",
  "It doesn't seem useful",
  "They live in another country",
  "This offer doesn't seem so interesting",
  "He wants to buy this thing",
  "I want to go there again",
  "I have a new car",
  "I want to go there one more time",
  "My friend wants to check it one more time",
  "I really want to know it",
  "He works here",
  "We want to know all these rules",
  "They want to learn English fast",
  "She wants to do it right now",
  "Its profit doesn't seem big",
  "We need it",
  "I want to go abroad",
  "He has a company",
  "Its profit seems so big",
  "He has a new house",
  "I don't want to tell you this thing",
  "I need to call him",
];

// lesson 12.2 practice======================================пров
[
  "Я не хочу говорить тебе об этой проблема",
  "Он не верят ему",
  "Она хочет жить в другом месте",
  "Я не хочу делать это прямо сейчас",
  "Я люблю её",
  "Я хочу тренироваться более регулярно",
  "Эти вещи меня вовсе не интересуют",
  "Я вижу, тебе реально нравится английский",
  "Моему партнёру нужно решить эту проблему",
  "Я хочу это знать",
  "У него есть доллары",
  "Она думает, деньги не делают людей счастливыми",
  "Я не хочу играть в компьютерные игры",
  "Я хотел бы выпить чашку чая",
  "Я хочу новый компьютер",
  "Я не понимаю этих людей",
  "Её нравится это место",
  "Я хотел бы стать бизнесменом",
  "У него хорошая машина",
  "Мне действительно нравится это место",
  "Она очень хорошо делает это",
  "Он думает, деньги не приносят людям счастье",
  "Ему нужно больше денег",
  "Мне действительно нравится этот плейлист",
  "Он не хочет делать это позже",
  "Я не хочу пить",
  "Её парень не знает об этой проблеме",
  "Он не хочет читать эти книги",
  "Он хочет читать те книги",
  "Я хочу улучшить свой английский",
  "Мне нужно решить ту проблему",
  "Я хочу это платье",
  "Мне нужно решить эти проблемы",
  "Мне нравится этот метод",
  "Она не играет в компьютерные игры",
  "Нам нужно заплатить за это",
  "Она хочет увидеть тебя прямо сейчас",
  "Мне нужно говорить по-английски правильно",
  "Мне нравится этот плейлист",
  "Все мои друзья думают так",
  "Мне действительно нужно выучить английский как можно быстрее",
  "Я знаю её",
  "Я хотел бы заказать это",
  "Я хочу говорить по-английски правильно",
  "Деньги не привлекают его",
  "Я хотел бы очень хорошо знать английский",
  "Я не знаю этого человека",
  "Мой партнёр не знает его",
  "Мне нужно говорить по-английски вовсе без каких-либо ошибок",
  "Я хочу новую квартиру",
  "Те вещи не кажутся странными",
];

[
  "I don't want to tell you about this problem",
  "They don't believe him",
  "She wants to leave in another place",
  "I won't want to do it right now",
  "I love her",
  "I want to train more regular",
  "This things don't interest me at all",
  "I see you really like English",
  "My partner needs to solve this problem",
  "I want to know it",
  "He has a dollars",
  "She thinks money doesn't makes people happy",
  "I don't want to play computer games",
  "I'd like to drink a cup of tea",
  "I want a new computer",
  "I don't understand this people",
  "Her likes this place",
  "I'd like to become businessman",
  "He has a good car",
  "I really like this place",
  "She does it very well",
  "He think money doesn't come people happyness",
  "He needs more money",
  "I really like this playlist",
  "He doesn't want to do it later",
  "I doesn't want to drink",
  "Her boyfriend doesn't know about this problem",
  "He doesn't want to read these books",
  "He wants to read those books",
  "I want to improve my English",
  "I need to solve that problem",
  "I want thisdress",
  "I want to solve these problems",
  "I like this method",
  "She doesn't play computer games",
  "We need to pay for it",
  "She wants to see you right now",
  "I need to speak English correctly",
  "I like this playlist",
  "All my friends think so",
  "I really need to learn English as soon as possible",
  "I know her",
  "I'd like to order it",
  "I want to speak English correctly",
  "Money doesn't attract him",
  "I'd like to know English very well",
  "I don't want this person",
  "My partner doesn't know him",
  "I need to speak English without any mistakes at all",
  "I want a new flat",
  "These things don't seem strange",
];

// lesson 13.1=================================
[
  "У него так много проблем",
  "Она часто ходит в парк",
  "Ей нужно пойти домой",
  "У неё есть интересные идеи",
  "Эта вещь вовсе не интересует меня",
  "Они не верят нам",
  "Я хотел бы стать менеджером",
  "Я хотел бы обсудить это с тобой",
  "Они всё знают",
  "Его девушка всё знает",
  "Я не заказываю еду там",
  "Мне нужно сделать это",
  "Это случается время от времени",
  "Моя сестра не хочет делать это позже",
  "Она хочет сделать это прямо сейчас",
  "Я хотел бы больше практики",
  "Я думаю, тебе нужно работать больше",
  "Мне реально нравится этот канал",
  "Моему другу нужен твой совет прямо сейчас",
  "Я люблю тебя",
  "Мой друг не согласен со мной",
  "Моему другу не нравится эта идея",
  "Мне реально нужно это знать",
  "Они иногда играют в компьютерные игры",
  "Я не верю тебе",
  "Его предложение кажется таким хорошим",
  "Ты всегда говоришь это",
  "Им нужно это",
  "Я не верю им",
  "Она всегда делает это вовремя",
  "Я не хочу думать об этом",
  "Мне нужно это",
  "Мой друг не думает так",
  "Это не помогает мне",
  "Тот метод не работает",
  "Этот метод реально работает",
  "Она не говорит мне эти вещи",
  "Я обычно прихожу домой рано",
  "Мой друг не пытается делать это",
  "Ты знаешь это лучше",
  "Они знают этого человека",
  "Я не хочу жить в том городе",
  "Все твои идеи кажутся интересными",
  "Я хочу поехать в другое место",
  "Нам нужно больше информации",
  "Мне нравится эта идея",
  "Мне нравятся все твои идеи",
  "Та вещь вовсе не интересует меня",
  "Мои родители хотят жить в другом месте",
  "Мне нужны деньги",
  "Мне реально нужен английский",
  "Его отцу нужны деньги",
];

[
  "He has so many problems",
  "She often goes to the park",
  "She needs to go home",
  "She needs interesting ideas",
  "This thing doesn't interesting me at all",
  "They don't believe us",
  "I'd like to become a manager",
  "I'd like to discuss it with you",
  "They knows something",
  "His girlfriend knows ewerything",
  "I don't order food there",
  "I need to do it",
  "It happens from time to time",
  "My sister doesn't want to do it later",
  "She wants to do it right now",
  "I'd like more practice",
  "I think you need to work more",
  "I really like this channel",
  "My friend needs your advice right now",
  "I love you",
  "My friend doesn't agree with me",
  "My friend doesn't like this idea",
  "I really need to know it",
  "They sometimes play to computer games",
  "I don't believe you",
  "His offer seems so good",
  "You always say it",
  "They need it",
  "I don't believe them",
  "She always does it ontime",
  "I don't want to think about it",
  "I need it",
  "My friend doesn't think so",
  "It doesn't help me",
  "That method doesn't work",
  "This method really works",
  "She doesn't tell me these things",
  "I usually come to home early",
  "My friend doesn't try to do it",
  "You know it better",
  "They know this person",
  "I don't want to live in that city",
  "All your ideas seem interesting",
  "I want to go in another place",
  "We need more information",
  "I like this idea",
  "I like all your ideas",
  "That thing doesn't interest me at all",
  "My parents wants to leave in anodhe place",
  "I need money",
  "I really need English",
  "His father needs money",
];

// lesson 13.2=====================================================
[
  "Мне нравится этот канал",
  "Я не хочу учиться там",
  "У нас нет каких-либо вопросов",
  "Её парень поддерживает её",
  "Мои друзья не верят ей",
  "У моего партнёра есть интересное предложение",
  "Ты не пытаешься выучить английский",
  "У него нет машины",
  "Мне нужно исправить эту ошибку",
  "Мне нужна эта информация снова",
  "Мне нужно выучить английский",
  "Она ходит в школу",
  "Мне нужно увидеть её",
  "Мы поддерживаем тебя",
  "Моя сестра не хочет учиться там",
  "Я хочу знать английский лучше",
  "Те уроки не кажутся полезными",
  "Эти уроки кажутся очень полезными",
  "Мне нужно говорить по-английски без ошибок",
  "Я действительно хочу это",
  "Мы часто отдыхаем там",
  "Мне нравится это видео",
  "Моуму другу нужна твоя помощь",
  "Этот урок помогает мне",
  "Я хотел бы сделать это",
  "Её английским кажется таким хорошим",
  "Его девушка не чувствует себя счастливой",
  "Их родители чувствуют себя такими счастливыми",
  "Я хотел бы чашку кофе",
  "Мой босс не видит её",
  "Я хочу купить новую квартиру",
  "Он не знает это",
  "Я хотел бы чашку чая",
  "Мне нужно говорить по-английски свободно",
  "Мне нужна хорошая машина",
  "Я хотел бы стать бизнесменом",
  "Я хочу говорить по-английски свободно и правильно",
  "Я хочу иметь хорошую работу",
  "Это предложение кажется таким странным",
  "Она не хочет обсуждать это",
  "Ей нужно это",
  "Мне действительно нужны твои уроки",
  "Мне нужно позвонить им",
  "Моему другу нравится этот отель",
  "Мы с моей девушкой часто ходим в парк",
  "Мой друг не думат так",
  "Она не чувствует себя счастливой",
  "Я не согласен с тобой",
  "У него есть идея",
  "Его босс не говорит свободно по-английски",
  "Мне нужен твой совет",
];

[
  "I like this channel",
  "I don't want to study there",
  "We don't have some questions",
  "Her boyfriend supports her",
  "My friends don't believe me",
  "My partner have an interesting offer",
  "You don't try to learn English",
  "He doesn't have a car",
  "I need to correct this mistake",
  "I need this information again",
  "I need to learn English",
  "She does to school",
  "I need to see her",
  "We support you",
  "My sister doesn't want to study there",
  "I want to know English better",
  "Those lessons don't seem useful",
  "These lessons seem very useful",
  "I need to speak English without mistakes",
  "I really want it",
  "We often relax there",
  "I like this video",
  "My friend wants your help",
  "This lesson helps me",
  "I'd like to do it",
  "Her English seems so good",
  "His girlfriend seems happy",
  "Their parents seem so happy",
  "I'd like a cup of coffee",
  "My boss doesn't see her",
  "I want to buy a new flat",
  "He doesn't know it",
  "I'd like a cup of tea",
  "I need to speak English fluently",
  "I need a good car",
  "I'd like to become a businessman",
  "I want to speak English fluently and correctly",
  "I want to have a good job",
  "This offer seems so strange",
  "She doesn't want to discuss it",
  "She needs it",
  "I really need your lessons",
  "I need to call them",
  "My friend likes this hotel",
  "My girlfriend and I often go to park",
  "My friend doesn't want so",
  "She doesn't feel happy",
  "I don't agree with you",
  "He has idea",
  "His boss doesn't speak English fluently",
  "I need your advice",
];


// lesoon 14==========================
// Present Simple (questions)
// Do + I/we/you/they + verb?
[
  "Ты знаешь это?",
  "Я делаю ошибки?",
  "Мы показываем хорошие результаты?",
  "Ты понимаешь меня?",
  "Они согласны с нами?",
  "Ты пытаешься улучшить этот результат?",
  "Ты работаешь над своими ошибками?",
  "У тебя есть свободное время?",
  "Ты поддерживаешь меня?",
  "Ты согласен со мной?",
  "Ты помнишь это?",
  "Ты всё помнишь?",
  "Ты знаешь об этой проблеме?",
  "Тебе нужна помощь?",
  "Тебе нужно больше денег?",
  "Тебе нужен мой совет?",
  "Ты поддерживаешь это решение?",
  "Ты хочешь учиться лучше?",
  "Ты хочешь знать свои ошибки?",
  "Тебе нужно решить эту проблему прямо сейчас?",
  "Тебе нравится это?",
  "Тебе нравится этот канал?",
  "Тебе нравится эта песня?",
  "Тебе нравится эта идея?",
  "Тебе нравится классическая музыка?",
  "Ты часто делаешь это?",
  "Ты часто слушаешь музыку?",
  "Ты часто ходишь туда?",
  "Ты часто пользуешься интернетом?",
  "Ты часто ходишь в зал?",
  "Ты часто посещаешь это место?",
  "Они часто обсуждают это?",
  "Они делают то же самое?",
  "У нас достаточно практики?",
  "У нас достаточно знаний?",
];

[
  "Do you know it?",
  "Do I make mistakes?",
  "Do we show good results?",
  "Do you understand me?",
  "Do you improve this result?",
  "Do you work on your mistakes?",
  "Do you have free time?",
  "Do you support me?",
  "Do you agree with me?",
  "Do you remember it?",
  "Do you remember everything?",
  "Do you know about this problem?",
  "Do you need help?",
  "Do you need more money?",
  "Do you need my advice?",
  "Do you support this decision?",
  "Do you want to learn better?",
  "Do you want to know your mistakes?",
  "Do you need to solve this problem right now?",
  "Do you like it?",
  "Do you like this channel?",
  "Do you like this song?",
  "Do you like this idea?",
  "Do you like classical music?",
  "Do you often do it?",
  "Do you often listen to musik?",
  "Do you often to go there?",
  "Do you often use the internet?",
  "Do you often go to the gym?",
  "Do you often visit this place?",
  "Do they often discuss it?",
  "Do they do the same?",
  "Do we enough practice?",
  "Do we enough knowledge?",
];

[
  "Ты всё помнишь?",
  "Они поддерживают нас?",
  "Тебе нравится это?",
  "Ты хочешь учиться лучше?",
  "Ты часто пользуешься интернетом?",
  "Ты часто ходишь в зал?",
  "Ты поддерживаешь его?",
  "Ты ходишь в школу?",
  "У нас достаточно знаний?",
  "Ты хочешь знать свои ошибки?",
  "Мы показываем хорошие результаты?",
  "Тебе нужно решить это проблему прямо сейчас?",
  "У тебя достаточно денег?",
  "У нас достаточно практики?",
  "Ты поддерживаешь его?",
  "Тебе нравится это платье?",
  "Они согласны с нами?",
  "Ты часто ходишь туда?",
  "Ты поддерживаешь меня?",
  "Тебе нравится то предложение?",
  "Ты часто слушаешь музыку?",
  "Ты ходишь на работу?",
  "Ты согласен с ним?",
  "Ты пытаешься улучшить этот результат?",
  "У тебя есть свободное время?",
  "Ты понимаешь меня?",
  "Ты поддерживаешь это решение?",
  "Ты работаешь над своими ошибками?",
  "Тебе действительно нравится эта идея?",
  "Тебе нужно больше денег?",
  "Ты согласен с ними?",
  "Я делаю ошибки?",
  "Ты помнишь это?",
  "Ты согласен с ней?",
  "Ты знаешь об этой проблеме?",
  "Ты часто делаешь это?",
  "Тебе нужна помощь?",
  "У меня достаточно денег?",
  "Ты согласен со мной?",
  "Ты часто посещаешь это место?",
  "Тебе нужен мой совет?",
  "Они поддерживают это решение?",
  "Они видят свои ошибки?",
  "Ты часто звонишь ему?",
];

[ "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
 "",
];
