const wordRusText = document.querySelectorAll('.word__rus-text');
let lesson3__1Rus = [
  "Она хочет сделать это",
  "Она смотрит телевизор",
  "У неё есть кот",
  "Он всегда делает это вовремя",
  "Он делает это каждый день",
  "Он скучает по тебе",
  "Она иногда ходит в кино",
  "Он иногда играет в компьютерные игры",
  "У него есть собака",
  "Она преподаёт это",
  "Он пытается найти работу",
  "Он идёт на работу",
  "Она чувствует себя такой счастлвой",
  "У неё есть интересные идеи",
  "Он часто ходит в кино",
  "Он иногда хочет сделать это",
  "Она скучает по тебе",
  "Он пытается делать это",
  "Она хочет пойти в парк",
  "У него есть деньги",
  "У него есть машина",
  "Он пытается помочь мне",
  "У него есть доллары",
  "У него есть предложение",
  "Он преподаёт английский",
  "Он пытается изучать английский",
  "У него есть дом",
  "Он делает это очень хорошо",
  "Он часто играет в компьютерные игры",
  "Он пытается понять это",
  "Она часто ходит в парк",
];

const wordEngText = document.querySelectorAll('.word__eng-text');
let lesson3__1Eng = [
"He wants to do it",
"She watches TV",
"She has a cat",
"She always does it on time",
"He does it on time",
"He does it every day",
"He misses you",
"She sometimes goes to the cinema",
"He sometimes plays computer games",
"He has a dog",
"She teaches it",
"He tryes to find a job",
"He goes to work",
"She feels so happy",
"She has interesting ideas",
"He often goes to the cinema",
"He sometimes wants to do it",
"She misses you",
"He tries to do it",
"She wants to go to the park",
"He has money",
"He has a car",
"He tryes to help me",
"He has dollars",
"He has an offer",
"He teaches English",
"She tries to learn English",
"He has a house",
"She does it very well",
"He often plays computer games",
"She tryes to understand it",
"She often goes to the park",
];

for (let i = 0; i < wordRusText.length; i++) {
  wordRusText[i].textContent = lesson3__1Rus[i];
  wordEngText[i].textContent = lesson3__1Eng[i];
}
