const wordRusText = document.querySelectorAll('.word__rus-text');
let lesson4Rus = [
  "Этот урок кажется интересным",
  "Эти уроки кажутся очень полезными",
  "Этот урок помогает мне",
  "Эти уроки помогают мне",
  "Твои уроки реально помогают",
  "Мой брат хочет это",
  "Моя сестра живёт там",
  "Мои родители знают это",
  "У моего друга есть машина",
  "Я",
  "Мой, моя, моё",
  "Мой босс знает всё",
  "Мой босс обычно читает все документы",
  "Мой босс обычно проверяет всю информфцию",
  "Мы",
  "Наш",
  "Наша мама думает так же",
  "Они",
  "Их",
  "Их идеи кажутся такими интересными",
  "Он",
  "Его",
  "У его отца есть машина",
  // "Он всегда заканчивает свою работу вовремя",
  // "Она обычно отдыхает дома",
  // "Она обычно отдыхает дома",
  // "Он пытается сделать это",
  // "Она пытается изучать английский",
  // "Он пытается найти работу",
  // "Он иногда играет в компьютерные игры",
  "Она",
  "Её",
  "Её брат часто говорит это",
  "Это",
  "Его, её(неодушевлённ.)",
  "У него есть компания",
  "Её прибыль кажется такой большой",
  "Моя девушка чувствует себя такой счастливой",
  "Мой бойфренд любит меня очень сильно",
  "Мой друг всегда поддерживает меня",
  "Мои друзья иногда говорят это",
  "Мои лучшие друзья всегда помогают мне",
  "Мой учитель обычно приходит на работу рано",
  "Мой отец обычно приходит на работу поздно",
];

const wordEngText = document.querySelectorAll('.word__eng-text');
let lesson4Eng = [
  "This lesson seems interesting",
  "These lessons seem very useful",
  "This lesson helps me",
  "These lessons help me",
  "Your lessons really help",
  "My brother wants it",
  "My sister lives there",
  "My parents know it",
  "My friend has a car",
  "I",
  "My",
  "My boss knows everything",
  "My boss usually reads all documents",
  "My boss usually check all the information",
  "We",
  "Our",
  "Our mother thinks the same",
  "They",
  "Their",
  "Their ideas seem so interesting",
  "He",
  "His",
  "His father has a car",
  // "He always finishes his work on time",
  // "She usually relaxes at home",
  // "She usually has a rest at home",
  // "He tries to do it",
  // "She tries to learn English",
  // "He tries to find a job",
  // "He sometimes plays computer games",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];

for (let i = 0; i < wordRusText.length; i++) {
  wordRusText[i].textContent = lesson4Rus[i];
  wordEngText[i].textContent = lesson4Eng[i];
}