const wordRusText = document.querySelectorAll('.word__rus-text');
let lesson3Rus = ["Он часто играет в компьютерные игры",
  "Я говорю по-английски",
  "Она знает это",
  "Он делает это каждый день",
  "Она ходит в школу",
  "Он ходит на работу",
  "Он часто ходит в кино",
  "Она часто ходит в парк",
  "Она делает это очень хорошо",
  "У него есть дом",
  "У неё есть машина",
  "У него есть машина",
  "У него есть собака",
  "У неё есть кот",
  "У него есть деньги",
  "У него есть доллар",
  "У него есть доллары",
  "У неё есть интересная идея",
  "У него есть предложение",
  "Она смотрит телевизор",
  "Он преподаёт английский",
  "Он скучает по тебе",
  "Я помню это очень хорошо",
  "Он всегда заканчивает свою работу вовремя",
  "Она обычно отдыхает дома",
  "Она обычно отдыхает дома",
  "Он пытается сделать это",
  "Она пытается изучать английский",
  "Он пытается найти работу",
  "Он иногда играет в компьютерные игры",
];

const wordEngText = document.querySelectorAll('.word__eng-text');
let lesson3Eng = [
  "He often plays computer games",
  "I speak English",
  "She knows it",
  "He does it every day",
  "She goes to school",
  "He goes to work",
  "He often goes to the cinema",
  "She often goes to the park",
  "She does it very well",
  "He has a house",
  "She has a car",
  "He has a car",
  "He has a dog",
  "She has a cat",
  "He has money",
  "He has a dollar",
  "He has dollars",
  "She has interesting ideas",
  "He has an offer",
  "She watches TV",
  "He teaches English",
  "He misses you",
  "I remember it wery well",
  "He always finishes his work on time",
  "She usually relaxes at home",
  "She usually has a rest at home",
  "He tries to do it",
  "She tries to learn English",
  "He tries to find a job",
  "He sometimes plays computer games",
]

for (let i = 0; i < wordRusText.length; i++) {
  wordRusText[i].textContent = lesson3Rus[i];
  wordEngText[i].textContent = lesson3Eng[i];
}

