const wordRusText = document.querySelectorAll('.word__rus-text');
let lesson4__1Rus = [
  "Я всё вижу",
  "Моя сестра живёт там",
  "Этот урок кажется интересным",
  "Этот урок помогает мне",
  "Я всё понимаю",
  "Мои родители знают это",
  "Её брат часто говорит это",
  "То предложение кажется странным",
  "Мой босс всегда говорит это",
  "Его уроки кажутся очень полезными",
  "Мой брат хочет это",
  "У его отца есть машина",
  "Мои родители хотят сделать это",
  "Твои уроки реально помогают",
  "Моя сестра учится там",
  "Эти уроки помогают мне",
  "Они всё знают",
  "Мой брат пытается сделать это",
  "Их идеи кажутся очень интересными",
  "Мой босс обычно проверяет всю информацию",
  "Моя сестра живёт в этом месте",
  "У моего друга есть машина",
  "У него есть компания",
  "Её прибыль кажется такой большой",
  "Мой босс всё знает",
  "Наша мама думает так же",
  "Мой босс читает все документы",
  "Эти уроки кажутся очень полезными",
  "Это предложение кажется очень интересным",
  "Это предложение выглядит очень интересным",
  "У этой компании есть деньги",
  "Эти уроки реально помогают",
  "Я чувствую это",
];

const wordEngText = document.querySelectorAll('.word__eng-text');
let lesson4__1Eng = [
  "I see everything",
  "My sister leaves there",
  "This lesson seems interesting",
  "This lesson helps me",
  "I understand everything",
  "My parents know it",
  "Her brother often says it",
  "That offer seems strange",
  "My boss always says it",
  "His lessons seem very useful",
  "Me brother wants it",
  "His father has a car",
  "My parents want to do it",
  "Your lessons really help",
  "My sister studies there",
  "This lessons help me",
  "They know everything",
  "My brother tries to do it",
  "Their ideas seem very interesting",
  "My boss usually shecks all the information",
  "My sister lives in this place",
  "My friend has a car",
  "He has a company",
  "Its profit seems so big",
  "My boss knows everything",
  "Our mother thinks the same",
  "My boss reeds all the documents",
  "These lessons seem very useful",
  "This offer seems very interseting",
  "This offer looks very interesting",
  "This company has money",
  "These lessons really help",
  "I feel it",
];


for (let i = 0; i < wordRusText.length; i++) {
  wordRusText[i].textContent = lesson4__1Rus[i];
  wordEngText[i].textContent = lesson4__1Eng[i];
}